// ordersData.js
export const ordersData = [
    {
      key: '1',
      orderNumber: '1001',
      customerName: 'John Doe',
      product: 'Steel Beam',
      quantity: 100,
      orderDate: '2024-03-10',
      deliveryStatus: 'Delivered',
    },
    {
      key: '2',
      orderNumber: '1002',
      customerName: 'Jane Smith',
      product: 'Aluminium Coil',
      quantity: 200,
      orderDate: '2024-03-12',
      deliveryStatus: 'In Transit',
    },
    {
      key: '3',
      orderNumber: '1003',
      customerName: 'Emily Johnson',
      product: 'Copper Wire',
      quantity: 50,
      orderDate: '2024-03-14',
      deliveryStatus: 'Processing',
    },
    {
      key: '4',
      orderNumber: '1004',
      customerName: 'Michael Brown',
      product: 'Zinc Sheets',
      quantity: 75,
      orderDate: '2024-03-15',
      deliveryStatus: 'Delivered',
    },
    {
      key: '5',
      orderNumber: '1005',
      customerName: 'Isabella Davis',
      product: 'Nickel Rods',
      quantity: 20,
      orderDate: '2024-03-17',
      deliveryStatus: 'Cancelled',
    },
    {
      key: '6',
      orderNumber: '1006',
      customerName: 'Matthew Wilson',
      product: 'Titanium Pipes',
      quantity: 30,
      orderDate: '2024-03-18',
      deliveryStatus: 'In Transit',
    },
    {
      key: '7',
      orderNumber: '1007',
      customerName: 'Ava Martinez',
      product: 'Iron Plates',
      quantity: 95,
      orderDate: '2024-03-19',
      deliveryStatus: 'Processing',
    },
    {
      key: '8',
      orderNumber: '1008',
      customerName: 'Oliver Anderson',
      product: 'Graphite Electrodes',
      quantity: 40,
      orderDate: '2024-03-21',
      deliveryStatus: 'Delivered',
    },
    {
      key: '9',
      orderNumber: '1009',
      customerName: 'Sophia Thomas',
      product: 'Lead Rolls',
      quantity: 60,
      orderDate: '2024-03-22',
      deliveryStatus: 'In Transit',
    },
    {
      key: '10',
      orderNumber: '1010',
      customerName: 'Lucas Jackson',
      product: 'Magnesium Coils',
      quantity: 85,
      orderDate: '2024-03-23',
      deliveryStatus: 'Processing',
    },
    // Daha fazla örnek veri ekleyerek toplamı 20'nin üzerine çıkarabilirsiniz
    {
      key: '11',
      orderNumber: '1011',
      customerName: 'Mia Harris',
      product: 'Steel Rivets',
      quantity: 120,
      orderDate: '2024-03-25',
      deliveryStatus: 'Delivered',
    },
    {
      key: '12',
      orderNumber: '1012',
      customerName: 'Amelia Clark',
      product: 'Alloy Beams',
      quantity: 110,
      orderDate: '2024-03-26',
      deliveryStatus: 'In Transit',
    },
    {
      key: '13',
      orderNumber: '1013',
      customerName: 'Ethan Lewis',
      product: 'Silver Plates',
      quantity: 100,
      orderDate: '2024-03-27',
      deliveryStatus: 'Cancelled',
    },
    {
      key: '14',
      orderNumber: '1014',
      customerName: 'Charlotte Walker',
      product: 'Gold Bars',
      quantity: 5,
      orderDate: '2024-03-29',
      deliveryStatus: 'Delivered',
    },
    {
      key: '15',
      orderNumber: '1015',
      customerName: 'Harper Hall',
      product: 'Silicon Sheets',
      quantity: 200,
      orderDate: '2024-03-30',
      deliveryStatus: 'Processing',
    },
    {
      key: '16',
      orderNumber: '1016',
      customerName: 'Evelyn Young',
      product: 'Ceramic Rods',
      quantity: 150,
      orderDate: '2024-04-01',
      deliveryStatus: 'In Transit',
    },
    {
      key: '17',
      orderNumber: '1017',
      customerName: 'Logan Allen',
      product: 'Plastic Tubes',
      quantity: 250,
      orderDate: '2024-04-02',
      deliveryStatus: 'Delivered',
    },
    {
      key: '18',
      orderNumber: '1018',
      customerName: 'Lily King',
      product: 'Rubber Hoses',
      quantity: 300,
      orderDate: '2024-04-03',
      deliveryStatus: 'Cancelled',
    },
    {
      key: '19',
      orderNumber: '1019',
      customerName: 'Aiden Wright',
      product: 'Fiberglass Wires',
      quantity: 100,
      orderDate: '2024-04-05',
      deliveryStatus: 'Processing',
    },
    {
      key: '20',
      orderNumber: '1020',
      customerName: 'Zoe Lopez',
      product: 'Carbon Fiber Panels',
      quantity: 45,
      orderDate: '2024-04-07',
      deliveryStatus: 'In Transit',
    },
    {
      key: '21',
      orderNumber: '1021',
      customerName: 'Benjamin Gonzalez',
      product: 'Composite Materials',
      quantity: 150,
      orderDate: '2024-04-08',
      deliveryStatus: 'Delivered',
    }
  ];
  