export const requestsData = [
  {
    key: "1",
    requestNumber: "1001",
    referenceNumber: "RN-1001",
    requestDate: "2024-03-10",
    details: "John Doe - Steel Beam - 100 Units",
    action: "View Details",
    state: "Delivered",
  },
  {
    key: "2",
    requestNumber: "1002",
    referenceNumber: "RN-1002",
    requestDate: "2024-03-12",
    details: "Jane Smith - Aluminium Coil - 200 Units",
    action: "View Details",
    state: "In Transit",
  },
  {
    key: "1",
    requestNumber: "1001",
    referenceNumber: "RN-1001",
    requestDate: "2024-03-10",
    details: "John Doe - Steel Beam - 100 Units",
    action: "View Details",
    state: "Delivered",
  },
  {
    key: "2",
    requestNumber: "1002",
    referenceNumber: "RN-1002",
    requestDate: "2024-03-12",
    details: "Jane Smith - Aluminium Coil - 200 Units",
    action: "View Details",
    state: "In Transit",
  },
  {
    key: "1",
    requestNumber: "1001",
    referenceNumber: "RN-1001",
    requestDate: "2024-03-10",
    details: "John Doe - Steel Beam - 100 Units",
    action: "View Details",
    state: "Delivered",
  },
  {
    key: "2",
    requestNumber: "1002",
    referenceNumber: "RN-1002",
    requestDate: "2024-03-12",
    details: "Jane Smith - Aluminium Coil - 200 Units",
    action: "View Details",
    state: "In Transit",
  },
  {
    key: "1",
    requestNumber: "1001",
    referenceNumber: "RN-1001",
    requestDate: "2024-03-10",
    details: "John Doe - Steel Beam - 100 Units",
    action: "View Details",
    state: "Delivered",
  },
  {
    key: "2",
    requestNumber: "1002",
    referenceNumber: "RN-1002",
    requestDate: "2024-03-12",
    details: "Jane Smith - Aluminium Coil - 200 Units",
    action: "View Details",
    state: "In Transit",
  },
  {
    key: "1",
    requestNumber: "1001",
    referenceNumber: "RN-1001",
    requestDate: "2024-03-10",
    details: "John Doe - Steel Beam - 100 Units",
    action: "View Details",
    state: "Delivered",
  },
  {
    key: "2",
    requestNumber: "1002",
    referenceNumber: "RN-1002",
    requestDate: "2024-03-12",
    details: "Jane Smith - Aluminium Coil - 200 Units",
    action: "View Details",
    state: "In Transit",
  },
  {
    key: "1",
    requestNumber: "1001",
    referenceNumber: "RN-1001",
    requestDate: "2024-03-10",
    details: "John Doe - Steel Beam - 100 Units",
    action: "View Details",
    state: "Delivered",
  },
  {
    key: "2",
    requestNumber: "1002",
    referenceNumber: "RN-1002",
    requestDate: "2024-03-12",
    details: "Jane Smith - Aluminium Coil - 200 Units",
    action: "View Details",
    state: "In Transit",
  },
  {
    key: "1",
    requestNumber: "1001",
    referenceNumber: "RN-1001",
    requestDate: "2024-03-10",
    details: "John Doe - Steel Beam - 100 Units",
    action: "View Details",
    state: "Delivered",
  },
  {
    key: "2",
    requestNumber: "1002",
    referenceNumber: "RN-1002",
    requestDate: "2024-03-12",
    details: "Jane Smith - Aluminium Coil - 200 Units",
    action: "View Details",
    state: "In Transit",
  },
];
